<?xml version="1.0" encoding="utf-8"?><Database Name="CodeReview" Class="LogsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-AVLPK7S;Initial Catalog=CodeReview;User ID=sa" SettingsObjectName="CodeReview.Properties.Settings" SettingsPropertyName="CodeReviewConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Logs" Member="Logs">
    <Type Name="Log">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="message" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>